version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt -t juyel
  build:
    commands:
      - echo "Zip the deployment package"
      - cd juyel
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Lambda function update"
      - aws lambda update-function-code --function-name demo-lambda --zip-file fileb://deployment_package.zip
      - echo "finished"
